import org.gradle.internal.os.OperatingSystem




plugins {
    id 'application'
}

group 'sky'
version '0.0.1'

repositories {
    mavenCentral()

}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        
        
    }
    test {
        java {
            srcDirs = ['test']
        }
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    manifest {
        manifest.attributes["Main-Class"] = "app.Main"
    }
}





project.ext.lwjglVersion = "3.4.1"
project.ext.jomlVersion = "1.10.8"
project.ext.kryoVersion = "5.6.2"
project.ext.gsonVersion = "2.13.2"
project.ext.jbulletVersion = "1.0.3"
project.ext.vecmathVersion = "1.5.2"
project.ext.flatlafVersion = "3.7.1"

switch (OperatingSystem.current()) {
    case OperatingSystem.LINUX:
        project.ext.lwjglNatives = "natives-linux"
        def osArch = System.getProperty("os.arch")
        if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
            project.ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
        } else if  (osArch.startsWith("ppc")) {
            project.ext.lwjglNatives += "-ppc64le"
        } else if  (osArch.startsWith("riscv")) {
            project.ext.lwjglNatives += "-riscv64"
        }
        break
    case OperatingSystem.MAC_OS:
        project.ext.lwjglNatives = System.getProperty("os.arch").startsWith("aarch64") ? "natives-macos-arm64" : "natives-macos"
        break
    case OperatingSystem.WINDOWS:
        def osArch = System.getProperty("os.arch")
        project.ext.lwjglNatives = osArch.contains("64")
                ? "natives-windows${osArch.startsWith("aarch64") ? "-arm64" : ""}"
                : "natives-windows-x86"
        break
}

dependencies {

    //JARs
    {
        implementation "com.esotericsoftware:kryo:$kryoVersion"
        implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
        implementation "org.lwjgl:lwjgl"
        implementation "org.lwjgl:lwjgl-glfw"
        implementation "org.lwjgl:lwjgl-stb"
        implementation "org.lwjgl:lwjgl-vma"
        implementation "org.lwjgl:lwjgl-vulkan"
        implementation "org.lwjgl:lwjgl-spvc"
        implementation "org.joml:joml:$jomlVersion"
        implementation "org.lwjgl:lwjgl-jawt"
        implementation files("thirdparty/lwjgl3-awt-0.2.3.jar")
        implementation "com.google.code.gson:gson:$gsonVersion"
        implementation "org.lwjgl:lwjgl-openal"
        implementation "com.github.stephengold:jbullet:$jbulletVersion"
        implementation "javax.vecmath:vecmath:$vecmathVersion"
        implementation "com.formdev:flatlaf:$flatlafVersion"


    }

    //Natives
    {
        runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
        runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
        runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"
        runtimeOnly "org.lwjgl:lwjgl-vma::$lwjglNatives"

        if (lwjglNatives == "natives-macos" || lwjglNatives == "natives-macos-arm64")
            runtimeOnly "org.lwjgl:lwjgl-vulkan::$lwjglNatives"

        runtimeOnly "org.lwjgl:lwjgl-spvc::$lwjglNatives"
        implementation "org.lwjgl:lwjgl-openal::$lwjglNatives"

    }

}


